name: Go Test

on:
  push:

jobs:

  build
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v4

    - name: Set up Go
      uses: actions/sett-up@v5
      with:
        go-version: '1.25.2'

    - name: Build
      run: go build -v .
